-- しずペットマップ：マネタイズ機能追加
-- 1) 施設のPR・クーポン
alter table public.facilities
  add column if not exists recommended boolean not null default false,
  add column if not exists sponsored boolean not null default false,
  add column if not exists coupon_enabled boolean not null default false,
  add column if not exists coupon_title text,
  add column if not exists coupon_code text,
  add column if not exists coupon_terms text;

-- 2) クリック計測
create table if not exists public.facility_events (
  id bigint generated by default as identity primary key,
  facility_id text not null,
  event_type text not null check (event_type in ('homepage','phone','route','coupon')),
  created_at timestamptz not null default now()
);

alter table public.facility_events enable row level security;

grant insert on table public.facility_events to anon, authenticated;
grant select on table public.facility_events to authenticated;

drop policy if exists facility_events_public_insert on public.facility_events;
create policy facility_events_public_insert
on public.facility_events
for insert
to anon, authenticated
with check (true);

drop policy if exists facility_events_admin_read on public.facility_events;
create policy facility_events_admin_read
on public.facility_events
for select
to authenticated
using (public.is_app_admin());

-- 確認
select
  count(*) as total_facilities,
  count(*) filter (where sponsored) as sponsored_count,
  count(*) filter (where coupon_enabled) as coupon_count
from public.facilities;
